// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwshsvqkruujoasjqaeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3c2hzdnFrcnV1am9hc2pxYWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjYyNTUsImV4cCI6MjA2MTAwMjI1NX0.s84cg1UrPIrSiy3AapdMlOQ6j44zcbGaOGWsQT5IfYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);