// This file is automatically generated. Do not edit it directly.
// Re-exporting from the central Supabase client to avoid multiple instances

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase } from '@/lib/supabase';
